import {examInfo,examParts,practicalTasks} from './examination.mjs';

export function examNotice(btn,showButton=true){return `<section class="examnotice" aria-label="Examinationsinformation"><div class="row between"><div><p class="eyebrow">MOMENT 5:8 · EXAMINATION</p><h2>5 november 2026</h2><p><strong>${examInfo.time} · Sal ${examInfo.room}</strong><br>Skriftligt på papper, utan hjälpmedel. Individuell praktisk examination vid samma tillfälle.</p></div>${showButton?btn('Träna de fyra skriftliga delarna','nav','data-view="prov"','secondary'):''}</div><div class="partgrid">${examParts.map(p=>`<div><strong>${p.threshold} %</strong><span>${p.title}</span></div>`).join('')}</div><p class="source">Varje skriftlig del bedöms separat. Du gör endast omexamination på den del du blivit underkänd på. Den praktiska delen med handterminal bedöms separat: U/G, godkäntgräns 80 %.</p><details class="source"><summary>Källa till examinationsvillkoren</summary><p>${examInfo.source}, återgiven ${examInfo.received}. Tiden gäller det gemensamma examinationstillfället. Antal frågor, poängfördelning och tid per del framgår inte av beskedet.</p></details></section>`;}

export function focusPicker(btn){return `<section class="panel focuspicker"><h2>Träna delarna som kräver 100 %</h2><p class="muted">Ett svar i taget, med facit efter ditt försök. Missade bokstäver och trafikuttryck hamnar i samma repetitionskö som dina övriga frågor.</p><div class="row">${examParts.slice(1).map(p=>btn(p.title,'focus-practice',`data-part="${p.id}"`,'secondary')).join('')}</div><p class="source">58 bokstaveringskort och 9 tillämpningar av trafikuttryck. Bokstaveringsorden återges enligt kursmaterialet; följ lärarens besked om skrivsätt.</p></section>`;}

export function partPicker(state,btn){return `<div class="exercisegrid">${examParts.map((p,i)=>{const last=state.history.findLast(h=>h.part===p.id);return `<section class="card"><div class="row between"><p class="eyebrow">SKRIFTLIG DEL ${i+1}</p><span class="badge">Godkäntgräns ${p.threshold} %</span></div><h2>${p.title}</h2><p>${p.description}</p><p class="muted">${last?`Senast sparat: ${last.known} av ${p.count} uppgifter bedömdes som Kunde själv.`:'Inget övningsresultat sparat för denna del.'}</p>${btn(`Starta ${p.title.toLocaleLowerCase('sv')}`,'start-exam',`data-part="${p.id}"`)}</section>`;}).join('')}</div>`;}

export function practicalView(state,{heading,btn,sources}){const done=practicalTasks.filter(t=>state.practical[t.id]===2).length;return `${heading('06 / PRAKTISK EXAMINATION','Öva med handterminalen.','Individuell examination vid samma tillfälle som den skriftliga: 5 november 2026 kl. 08.15–10.00, sal 1103N2.')}<div class="practicalintro"><div class="panel dark"><p class="eyebrow" style="color:var(--lime)">SEPARAT BEDÖMNING</p><h2>U/G · 80 %</h2><p>Detta är examinatorns godkäntgräns för den praktiska delen. Den bedöms separat från den skriftliga.</p><p class="source" style="color:#cfdeeb">Källa: ${examInfo.source}, återgiven ${examInfo.received}.</p></div><div class="panel"><h2>${done} av 7 områden övade självständigt</h2><p>Checklistan visar din egen träning. De sju rubrikerna är inte sju likvärdiga examinationspoäng. Poängfördelningen har inte meddelats, därför beräknas inget praktiskt godkändresultat här.</p></div></div><p class="notice">Gör uppgifterna på utbildningens handterminal enligt lärarens instruktioner. Webbövningarna ger stöd för arbetsgången. Menyer och knappar kan skilja sig med modell och programmering.</p><div class="stack">${practicalTasks.map(t=>`<section class="panel"><h2>${t.title}</h2><p>${t.task}</p><details><summary>Visa övningsstöd och kontrollpunkter</summary><ul class="source-list">${t.checks.map(c=>`<li>${c}</li>`).join('')}</ul></details><div class="toolbar"><label class="field">Min träning: ${t.title}<select data-practical="${t.id}">${['Inte övat på terminal','Övat med stöd','Utfört självständigt'].map((label,n)=>`<option value="${n}" ${(state.practical[t.id]||0)===n?'selected':''}>${label}</option>`).join('')}</select></label>${t.exercise?btn('Träna arbetsgången på skärmen','exercise',`data-id="${t.exercise}"`,'secondary'):btn('Träna kunskapsfrågorna','topic',`data-id="${t.topics[0]}"`,'secondary')}</div>${sources({...t,topic:t.topics[0]})}</section>`).join('')}</div><p class="notice">Samtliga 31 delmoment ingår fortfarande i den breda examinationsförberedelsen. Här lyfts de sju områden som examinatorn särskilt anger för den praktiska delen.</p>`;}
